### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Geczy** [eugv86/Robinhood-Ninja#3]
But does it offer any features that the robinhood.com web app doesn't?

**Comment by eugv86** [comment]
Not really, Just a StockTwits feed.  I'm looking to add some unique features latter on. The biggest difference is in the UI (I personally prefer my app but I'm biased).  I built this before Robinhood had it's platform up and running. Is there anything you want to see in this platform that Robinhood.com doesn't offer?

**Comment by Geczy** [comment]
Basically automatic trading

**Comment by eugv86** [comment]
@Geczy looks like that's something you are working on already, no?
