### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by devteam4509** [eugv86/Robinhood-Ninja#6]
After installing , getting some reverse proxy login issue.
it seems the proxy url is not resolvable

Attached images
![Screenshot (1589)](https://user-images.githubusercontent.com/9738854/61448321-53de0000-a970-11e9-9b7d-2d768ef3ea29.png)

**Comment by eugv86** [comment]
The proxy service has been shut down.  Please create your own or use the app locally with a chrome extension "Allow-Control-Allow-Origin". 

You would also need to remove a small script that directs all api.robinhood.com calls to use the proxy in the index.html page or modify to use your own proxy service.
